### ISSUE TITLE
`config` and `layout` props should be `Partial`

### ISSUE THREAD

**Issue by nmanoogian** [davidctj/react-plotlyjs-ts#2]
Hi there -- great project! I just noticed that I'm being required to specify *all* of the layout props to the `PlotlyChart` element. Should the `config` and layout` props be Partials?

**Comment by davidctj** [comment]
Hi @alkaline9500 , thanks for point that bug, I've fixed a new version 2.1.0, plz try that  and let me know

**Comment by nmanoogian** [comment]
Great work! It's working perfectly now. Thanks!
