### ISSUE TITLE
Latest package version from master isn't published to npm

### ISSUE THREAD

**Issue by iburakov** [davidctj/react-plotlyjs-ts#7]
Hi! It seems that current latest version of the package in master (2.2.1 after merging PR #6) isn't published to npm repo as [it has only 2-year-old 2.1.0](https://www.npmjs.com/package/react-plotlyjs-ts) with "latest" tag on it. 

I'm using it in one of my projects and at some point additional plotly event handlers ("plotly_legendclick", etc.) were required. They aren't available in 2.1.0, although were added by PR #4 and current master have them all. Sadly, I was unable to update the package using npm. Making it possible would be very helpful :)

PS.  Thanks for the convenient wrapper!

**Comment by davidctj** [comment]
@iburakov thanks for pointing this. I've published 2.2.1 to npm now.
